services:
  redis:
    image: redis
  web:
    build:
      context: .
    environment:
      FLASK_APP: run
      FLASK_DEBUG: 1
    volumes:
      - .:/app
    command: flask run -h 0.0.0.0
    ports:
      - 5000:5000
  celery:
    build:
        context: .
    volumes:
      - .:/app
    command: celery -A make_celery.celery_app worker --loglevel=info
    depends_on:
      - redis
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis